# Site settings
title: MagneticMule
email: magneticmule@gmail.com
description: Some Stuff made with a few things by Thomas D. Sweeney
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: TomDSweeney
github_username:  magneticmule
google_plus_username: +thomas_sweeney
tumblr_account: mrtommy
flickr_account: skywriter

# Build settings
markdown: kramdown
